(add-to-list 'auto-mode-alist '("\\.bash$'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.csh$'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.fish$'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.ksh$'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.sh$'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.tcsh$'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.tmuxtheme$'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.zsh$" . sh-mode))
