(defun sh-mode-customize ()
  (interactive)
  (flyspell-prog-mode)
  (flycheck-mode)
  (linum-mode t)
  (fci-mode)
  (hs-minor-mode 1)
  (auto-complete-mode)
  (whitespace-mode)
  (subword-mode)
  (setq sh-basic-offset 2)
  (setq sh-indentation 2)
  (setq highlight-indentation-offset 2)
  (setq whitespace-action (quote (auto-cleanup)))
  (highlight-indentation-mode)
  (define-key sh-mode-map (kbd "RET") 'reindent-then-newline-and-indent))

(add-hook 'sh-mode-hook 'sh-mode-customize)
