(load-file (concat dotfiles-dir "modes/sh-mode/autoload.el"))
(load-file (concat dotfiles-dir "modes/sh-mode/auto-mode-alist.el"))
(load-file (concat dotfiles-dir "modes/sh-mode/customize.el"))
(load-file (concat dotfiles-dir "modes/sh-mode/hooks.el"))
(load-file (concat dotfiles-dir "modes/sh-mode/indent.el"))
(load-file (concat dotfiles-dir "modes/sh-mode/sh-script.el"))
